import 'dart:convert';
import 'dart:typed_data';

import 'package:backend/utils/pan_crypto.dart';
import 'package:test/test.dart';

void main() {
  // 32-byte key (64 hex chars), fixed for determinism.
  const keyHex =
      '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef';

  group('PanCrypto', () {
    test('round-trips a PAN', () {
      const pan = 'ABCDE1234F';
      final sealed = PanCrypto.encrypt(pan, keyHex: keyHex);
      expect(PanCrypto.decrypt(sealed, keyHex: keyHex), pan);
    });

    test('emits web wire format [12B IV][ciphertext][16B tag]', () {
      const pan = 'ABCDE1234F';
      final sealed = PanCrypto.encrypt(pan, keyHex: keyHex);
      // 12 (IV) + len(pan) ciphertext + 16 (tag)
      expect(sealed.length, 12 + utf8.encode(pan).length + 16);
    });

    test('ciphertext is non-deterministic (random IV)', () {
      const pan = 'ABCDE1234F';
      final a = PanCrypto.encrypt(pan, keyHex: keyHex);
      final b = PanCrypto.encrypt(pan, keyHex: keyHex);
      expect(a, isNot(equals(b)));
      // ...but both decrypt to the same plaintext.
      expect(PanCrypto.decrypt(a, keyHex: keyHex), pan);
      expect(PanCrypto.decrypt(b, keyHex: keyHex), pan);
    });

    test('wrong key fails to decrypt (auth tag rejects)', () {
      final sealed = PanCrypto.encrypt('ABCDE1234F', keyHex: keyHex);
      const otherKey =
          'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff';
      expect(
        () => PanCrypto.decrypt(sealed, keyHex: otherKey),
        throwsA(isA<Object>()),
      );
    });

    test('missing/short key fails closed on encrypt', () {
      expect(() => PanCrypto.encrypt('ABCDE1234F', keyHex: ''),
          throwsA(isA<StateError>()));
      expect(() => PanCrypto.encrypt('ABCDE1234F', keyHex: 'abcd'),
          throwsA(isA<StateError>()));
    });

    test('decrypts a real Node-produced fixture (cross-app compatibility)', () {
      // Generated by Node's crypto (the same primitive familiarise_web
      // pan-crypto.ts uses) with the key above, PAN 'ABCDE1234F', and a fixed
      // IV 0x0102..0c, as base64 of [IV||ciphertext||16B tag]:
      //   node -e "const {createCipheriv}=require('crypto');
      //     const k=Buffer.from(KEY,'hex'),iv=Buffer.from('0102...0c','hex');
      //     const c=createCipheriv('aes-256-gcm',k,iv);
      //     const e=Buffer.concat([c.update('ABCDE1234F'),c.final()]);
      //     console.log(Buffer.concat([iv,e,c.getAuthTag()]).toString('base64'))"
      // This proves the Dart decryptor reads Node-encrypted ciphertext.
      const nodeFixtureB64 =
          'AQIDBAUGBwgJCgsMhv/YC1CS7ptF2a8fdWIyaZYUhYqWHkkhlYA=';
      final sealed = Uint8List.fromList(base64.decode(nodeFixtureB64));
      expect(PanCrypto.decrypt(sealed, keyHex: keyHex), 'ABCDE1234F');
    });
  });
}
