import 'consultant_profile.dart';
import 'appointment.dart';
import 'consultation_plan.dart';
import 'domain.dart';
import 'auth/user_model.dart';

class MockData {
  static final List<Domain> domains = [
    Domain(
      id: '1',
      name: 'Healthcare',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Domain(
      id: '2',
      name: 'Technology',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Domain(
      id: '3',
      name: 'Business',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Domain(
      id: '4',
      name: 'Legal',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Domain(
      id: '5',
      name: 'Finance',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
  ];

  static final List<ConsultantProfile> consultants = [
    ConsultantProfile(
      id: '1',
      name: 'Dr. Tyler Lucero',
      description: 'Experienced surgeon with over 15 years in cardiovascular surgery. Specializes in minimally invasive procedures.',
      qualifications: 'MD, FACS, Board Certified Cardiovascular Surgeon',
      specialization: 'Cardiovascular Surgery',
      experience: 15.0,
      rating: 4.9,
      domainId: '1',
      domainName: 'Healthcare',
      userId: 'user1',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400',
      subDomains: ['Surgery', 'Cardiology'],
      tags: ['Heart Surgery', 'Minimally Invasive', 'Emergency Care'],
      reviewCount: 127,
    ),
    ConsultantProfile(
      id: '2',
      name: 'Dr. Mya Guzman',
      description: 'Dedicated pediatrician with expertise in child development and preventive care.',
      qualifications: 'MD, Board Certified Pediatrician',
      specialization: 'Pediatrics',
      experience: 8.0,
      rating: 4.8,
      domainId: '1',
      domainName: 'Healthcare',
      userId: 'user2',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400',
      subDomains: ['Pediatrics', 'Child Development'],
      tags: ['Children', 'Vaccines', 'Development'],
      reviewCount: 89,
    ),
    ConsultantProfile(
      id: '3',
      name: 'Dr. Sarah Chen',
      description: 'Mental health specialist focusing on anxiety, depression, and cognitive behavioral therapy.',
      qualifications: 'PhD Clinical Psychology, Licensed Therapist',
      specialization: 'Clinical Psychology',
      experience: 12.0,
      rating: 4.7,
      domainId: '1',
      domainName: 'Healthcare',
      userId: 'user3',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      image: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=400',
      subDomains: ['Psychology', 'Therapy'],
      tags: ['CBT', 'Anxiety', 'Depression', 'Mindfulness'],
      reviewCount: 156,
    ),
    ConsultantProfile(
      id: '4',
      name: 'Alex Rodriguez',
      description: 'Full-stack developer and tech consultant with expertise in mobile and web applications.',
      qualifications: 'BS Computer Science, AWS Certified Solutions Architect',
      specialization: 'Software Development',
      experience: 10.0,
      rating: 4.6,
      domainId: '2',
      domainName: 'Technology',
      userId: 'user4',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
      subDomains: ['Software Development', 'Cloud Computing'],
      tags: ['React', 'Flutter', 'AWS', 'Node.js'],
      reviewCount: 73,
    ),
    ConsultantProfile(
      id: '5',
      name: 'Emma Thompson',
      description: 'Business strategy consultant helping startups scale and optimize operations.',
      qualifications: 'MBA Harvard Business School, Former McKinsey Associate',
      specialization: 'Business Strategy',
      experience: 7.0,
      rating: 4.8,
      domainId: '3',
      domainName: 'Business',
      userId: 'user5',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      image: 'https://images.unsplash.com/photo-1494790108755-2616c6db1a14?w=400',
      subDomains: ['Strategy', 'Operations'],
      tags: ['Startups', 'Scaling', 'Operations', 'Growth'],
      reviewCount: 92,
    ),
  ];

  static final List<ConsultationPlan> consultationPlans = [
    ConsultationPlan(
      id: '1',
      title: 'Initial Medical Consultation',
      description: 'Comprehensive medical consultation with diagnosis and treatment recommendations',
      durationInHours: 1.0,
      price: 15000, // ₹150
      language: 'English',
      level: 'All Levels',
      prerequisites: 'Medical history and current symptoms',
      materialProvided: 'Medical report and treatment plan',
      learningOutcomes: ['Accurate diagnosis', 'Treatment plan', 'Prevention strategies'],
      consultantProfileId: '1',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    ConsultationPlan(
      id: '2',
      title: 'Child Development Assessment',
      description: 'Complete assessment of your child\'s physical and mental development',
      durationInHours: 1.5,
      price: 12000, // ₹120
      language: 'English',
      level: 'Parents',
      prerequisites: 'Child\'s medical history',
      materialProvided: 'Development report and recommendations',
      learningOutcomes: ['Development status', 'Milestone tracking', 'Parenting tips'],
      consultantProfileId: '2',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    ConsultationPlan(
      id: '3',
      title: 'Mental Health Consultation',
      description: 'Initial therapy session for anxiety, depression, or stress management',
      durationInHours: 1.0,
      price: 20000, // ₹200
      language: 'English',
      level: 'All Levels',
      prerequisites: 'Open mind and willingness to share',
      materialProvided: 'Coping strategies and resources',
      learningOutcomes: ['Understanding triggers', 'Coping mechanisms', 'Treatment plan'],
      consultantProfileId: '3',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
  ];

  static final List<Appointment> upcomingAppointments = [
    Appointment(
      id: '1',
      appointmentType: AppointmentType.consultation,
      consultationId: 'consultation_1',
      title: 'Follow-up Consultation with Dr. Tyler Lucero',
      description: 'Follow-up for chest pain consultation',
      slots: [
        AppointmentSlot(
          id: 'slot_1',
          slotStartTimeInUTC: DateTime.now().add(const Duration(days: 2, hours: 14)),
          slotEndTimeInUTC: DateTime.now().add(const Duration(days: 2, hours: 15)),
          isTentative: false,
          appointmentId: '1',
          createdAt: DateTime.now(),
          updatedAt: DateTime.now(),
        ),
      ],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Appointment(
      id: '2',
      appointmentType: AppointmentType.consultation,
      consultationId: 'consultation_2',
      title: 'Therapy Session with Dr. Sarah Chen',
      description: 'Initial therapy session for anxiety management',
      slots: [
        AppointmentSlot(
          id: 'slot_2',
          slotStartTimeInUTC: DateTime.now().add(const Duration(days: 5, hours: 10)),
          slotEndTimeInUTC: DateTime.now().add(const Duration(days: 5, hours: 11)),
          isTentative: false,
          appointmentId: '2',
          createdAt: DateTime.now(),
          updatedAt: DateTime.now(),
        ),
      ],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
  ];

  static final User mockUser = User(
    id: 'mock_user_1',
    name: 'Eleanor Padilla',
    email: 'eleanor@example.com',
    role: UserRole.consultee,
    onlineStatus: true,
    image: 'https://images.unsplash.com/photo-1494790108755-2616c6db1a14?w=400',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  );

  // Mock patient data for the patient card shown in the images
  static final Map<String, dynamic> patientData = {
    'name': 'Eleanor Padilla',
    'gender': 'Female',
    'dateOfBirth': '17/03/1992',
    'patientId': '349UDh-098',
    'heartRate': '78 bpm',
    'bloodType': 'A+',
    'height': '169',
    'weight': '59',
    'chronicDiseases': ['Hypertension', 'Diabetes Type 2'],
    'allergies': ['Penicillin', 'Shellfish'],
    'operations': ['Appendectomy (2018)', 'Gallbladder Surgery (2020)'],
  };
} 